version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/my-app1
hooks:
  ApplicationStop:
    - location: codedeploy_application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: codedeploy_before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: codedeploy_after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy_application_start.sh
      timeout: 300
      runas: ubuntu
