version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/my-app1
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: Script/codedeploy_before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: Script/codedeploy_after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: Script/codedeploy_application_start.sh
      timeout: 300
      runas: ubuntu
