name: Build and Deploy to UAT and PRD
on:
  push:
  workflow_dispatch:  # Allows manual triggering

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      build_type: ${{ steps.set_build_type.outputs.build_type }}  # Define output
    steps:

      - name: Set environment variable
        id: set_build_type  # Add step ID for outputs
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "BUILD_TYPE=PRD" >> $GITHUB_ENV
            echo "build_type=PRD" >> $GITHUB_OUTPUT  # Set output
          elif [[ "${{ github.ref_name }}" == "UAT" ]]; then
            echo "BUILD_TYPE=UAT" >> $GITHUB_ENV
            echo "build_type=UAT" >> $GITHUB_OUTPUT  # Set output
          fi
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ env.BUILD_TYPE }}-latest

      - name: Create Docker image tag file
        run: |
          mkdir -p .github
          echo "${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ env.BUILD_TYPE }}-latest" > .github/docker-image-tag.txt

      - name: Upload Docker image tag
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tag
          path: .github/docker-image-tag.txt
          retention-days: 1

          
  deploy-uat:
    name: Deploy to UAT
    needs: build
    if: ${{ needs.build.outputs.build_type == 'UAT' }}  # Use job output
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: UAT
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ vars.EC2_HOST }}
      EC2_USER: ${{ vars.EC2_USER }}

  deploy-prd:
    name: Deploy to PRD
    needs: build
    if: ${{ needs.build.outputs.build_type == 'PRD' }}  # Use job output
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: PRD
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ vars.EC2_HOST }}
      EC2_USER: ${{ vars.EC2_USER }}
