name: Build and Deploy to UAT and PRD
on:
  push:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.ref_name }}-latest

      - name: Upload Docker image tag
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tag
          path: |
            .github/docker-image-tag.txt
          retention-days: 1
        #run: |
        #  echo "${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.ref_name }}-latest" > .github/docker-image-tag.txt

  deploy-uat:
    name: Deploy to UAT
    needs: build
    if: github.ref == 'refs/heads/uat'
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: UAT
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ vars.EC2_HOST }}
      EC2_USER: ${{ vars.EC2_USER }}

  deploy-prd:
    name: Deploy to PRD
    needs: build
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: PRD
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST: ${{ vars.EC2_HOST }}
      EC2_USER: ${{ vars.EC2_USER }}
